on:
  push:
    branches: [ main ]
name: Deploy website on push
jobs:
  web-deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server : ${{ secrets.FTP_SERVER }}
        username : ${{ secrets.FTP_USER }}
        password : ${{ secrets.FTP_PASS }}
        protocol : ftp
        port : ${{ secrets.PORT }}
        exclude : .git*
